# execution-environment/execution-environment.yml
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9

dependencies:
  python_interpreter:
    package_system: python3.11
    python_path: /usr/bin/python3.11

  ansible_core:
    # Require minimum of 2.15 to get ansible-inventory --limit option
    package_pip: ansible-core>=2.15.0rc2,<2.16

  ansible_runner:
    package_pip: ansible-runner

  system:
  - openssh-clients
  - sshpass

  galaxy: requirements.yml
  system: binddep.txt
  python: requirements.txt

additional_build_steps:
  append_base:
    - RUN pip3 uninstall --yes python_freeipa && pip3 install python_freeipa
    - RUN $PYCMD -m pip install -U pip
  append_final:
    - COPY --from=quay.io/ansible/receptor:devel /usr/bin/receptor /usr/bin/receptor
    - RUN mkdir -p /var/run/receptor
    - RUN git lfs install --system
    # SymLink `python` -> `python3.11`
    - RUN alternatives --install /usr/bin/python python /usr/bin/python3.11 311
