---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhat_cop.tower_configuration
  - name: community.general
  - name: community.network
  - name: ansible.posix
  - name: fortinet.fortimanager
  - name: fortinet.fortios
    version: 1.1.7
...
